#!/bin/bash
set -e

# ---------------------------------------------------------
# 04_annotation.sh
# Peak annotation for LUAD MYC ChIP-seq (A549)
# ---------------------------------------------------------

# Input MACS2 peak file
PEAKS="macs2_results/MYC_combined_peaks.narrowPeak"

# Output directory
OUTDIR="peaks"
mkdir -p $OUTDIR

echo "Annotating peaks using HOMER annotatePeaks.pl..."

# annotatePeaks.pl <peaks> hg38 > annotated_file
annotatePeaks.pl $PEAKS hg38 > $OUTDIR/MYC_peaks_annotated.bed

echo "Extracting unique gene list (column 8 of HOMER output)..."

cut -f 8 $OUTDIR/MYC_peaks_annotated.bed | sort -u > $OUTDIR/MYC_genes.txt

echo "Annotated peaks: peaks/MYC_peaks_annotated.bed"
echo "Gene list:peaks/MYC_genes.txt"
